"""Paper execution package for Core MVP virtual fills."""

from src.execution.broker import PaperBroker
from src.execution.ticks import InstrumentType, tw_instrument_type, tw_tick_for
from src.execution.types import (
    BROKER_APPROVED,
    BROKER_REJECTED_INSUFFICIENT_CASH,
    BROKER_REJECTED_INSUFFICIENT_HOLDINGS,
    BROKER_REJECTED_LEVERAGE_FORBIDDEN,
    BROKER_REJECTED_MARGIN_FORBIDDEN,
    BROKER_REJECTED_MIN_NOTIONAL,
    BROKER_REJECTED_NON_VIRTUAL_ORDER,
    BROKER_REJECTED_PRICE_TICK_VIOLATION,
    BROKER_REJECTED_PRIVATE_API_FORBIDDEN,
    BROKER_REJECTED_REAL_ORDERS_FORBIDDEN,
    BROKER_REJECTED_RISK_INTENT_MISMATCH,
    BROKER_REJECTED_RISK_NOT_APPROVED,
    BROKER_REJECTED_SYMBOL_MISMATCH,
    BROKER_REJECTED_ZERO_QUANTITY_AFTER_ROUNDING,
    BrokerAcceptedOrder,
    BrokerAccountView,
    BrokerRejectedOrder,
    PaperBrokerError,
    PaperBrokerParameters,
    PaperBrokerResult,
    PaperMarketPrice,
)

__all__ = [
    "BROKER_APPROVED",
    "BROKER_REJECTED_INSUFFICIENT_CASH",
    "BROKER_REJECTED_INSUFFICIENT_HOLDINGS",
    "BROKER_REJECTED_LEVERAGE_FORBIDDEN",
    "BROKER_REJECTED_MARGIN_FORBIDDEN",
    "BROKER_REJECTED_MIN_NOTIONAL",
    "BROKER_REJECTED_NON_VIRTUAL_ORDER",
    "BROKER_REJECTED_PRICE_TICK_VIOLATION",
    "BROKER_REJECTED_PRIVATE_API_FORBIDDEN",
    "BROKER_REJECTED_REAL_ORDERS_FORBIDDEN",
    "BROKER_REJECTED_RISK_INTENT_MISMATCH",
    "BROKER_REJECTED_RISK_NOT_APPROVED",
    "BROKER_REJECTED_SYMBOL_MISMATCH",
    "BROKER_REJECTED_ZERO_QUANTITY_AFTER_ROUNDING",
    "BrokerAcceptedOrder",
    "InstrumentType",
    "BrokerAccountView",
    "BrokerRejectedOrder",
    "PaperBroker",
    "PaperBrokerError",
    "PaperBrokerParameters",
    "PaperBrokerResult",
    "PaperMarketPrice",
    "tw_instrument_type",
    "tw_tick_for",
]
